services:
  #=============================================================================
  # DATABASE SERVICE
  #=============================================================================
  db-ws-solutions:
    container_name: db-ws-solutions
    image: mcr.microsoft.com/mssql/server:2022-CU19-GDR1-ubuntu-22.04  # Microsoft SQL Server 2022 - version 2022-CU19-GDR1 - last updated on 2025-07-08
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA} #accept the end user license agreement
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD} #set the SA password
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_DOCKER}" # map the host port to the container port
    volumes:
      - db_data:/var/opt/mssql # Persistent storage for database files
      - ./WS-Rental-Solutions-database/scripts-sql:/scripts-sql:ro
    networks:
      - ws-solutions-network
    restart: unless-stopped # Always restart unless stopped manually
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  #SQL tool, to creat DecolaTrips_DB
  sql-tools:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sql-tools
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./WS-Rental-Solutions-database/scripts-sql:/scripts-sql
    networks:
      - ws-solutions-network
    depends_on:
      - db-ws-solutions
  
  backend-auth-service-ws-solutions:
    build:
      context: ./WS-Rental-Solutions-backend/WS-Rental-Solutions-auth-service
      dockerfile: Dockerfile
    container_name: backend-auth-service-ws-solutions
    ports:
      - "8081:8080"
    volumes:
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-auth-service/src:/app/src
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-auth-service/pom.xml:/app/pom.xml
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-auth-service/src/main/resources:/app/src/main/resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      #- API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET}
    networks:
      - ws-solutions-network
    depends_on:
      #- db-mssql
      - sql-tools

  backend-api-gateway-service-ws-solutions:
    build:
      context: ./WS-Rental-Solutions-backend/WS-Rental-Solutions-api-gateway-service
      dockerfile: Dockerfile
    container_name: backend-api-gateway-service-ws-solutions
    ports:
      - "8080:8080"
    volumes:
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-api-gateway-service/src:/app/src
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-api-gateway-service/pom.xml:/app/pom.xml
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-api-gateway-service/src/main/resources:/app/src/main/resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev

    networks:
      - ws-solutions-network
  backend-person-service-ws-solutions:
    build:
      context: ./WS-Rental-Solutions-backend/WS-Rental-Solutions-person-service
      dockerfile: Dockerfile
    container_name: backend-person-service-ws-solutions
    ports:
      - "8082:8080"
    volumes:
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-person-service/src:/app/src
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-person-service/pom.xml:/app/pom.xml
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-person-service/src/main/resources:/app/src/main/resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev

    networks:
      - ws-solutions-network

  backend-property-service-ws-solutions:
    build:
      context: ./WS-Rental-Solutions-backend/WS-Rental-Solutions-property-service
      dockerfile: Dockerfile
    container_name: backend-property-service-ws-solutions
    ports:
      - "8083:8080"
    volumes:
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-property-service/src:/app/src
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-property-service/pom.xml:/app/pom.xml
      - ./WS-Rental-Solutions-backend/WS-Rental-Solutions-property-service/src/main/resources:/app/src/main/resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev

    networks:
      - ws-solutions-network


volumes:
  db_data:

networks:
  ws-solutions-network:
    driver: bridge